version: "2"

linters:
  enable:
    - asciicheck
    - bidichk
    - errcheck
    - errorlint
    - exhaustive
    - gocritic
    - govet
    - ineffassign
    - nilerr
    - staticcheck
    - unconvert
    - unused

formatters:
  enable:
    - gofmt
    - goimports

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
